In [1]:
import pandas as pd

In [11]:
dt = pd.read_csv('Amazon_BestSelling_Books_500.csv')

In [3]:
dt.head()

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
0,1,The Let Them Theory,Mel Robbins,Non-Fiction,Self-Help,Paperback,14.99,4.7,98000.0,52.0,Hay House,2024.0,978-1-13278-859-4,112.0,View
1,2,The Dinner Party,Freida McFadden,Fiction,Psychological Thriller,Paperback,11.69,4.3,1800.0,12.0,Sourcebooks Landmark,2025.0,978-3-76237-716-0,175.0,View
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,978-4-30379-320-5,64.0,View
3,4,The Correspondent: A Novel,Virginia Evans,Fiction,Literary Fiction,Hardcover,19.58,4.6,87363.0,28.0,Random House,2025.0,978-6-20328-665-4,143.0,View
4,5,Atomic Habits,James Clear,Non-Fiction,Self-Help / Productivity,Paperback,16.99,4.8,120000.0,220.0,Avery,2018.0,978-7-93320-954-5,237.0,View

In [4]:
dt.describe()

,Rank,Price (USD),Rating,Reviews,Weeks on List,Year Published,Amazon BSR
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,16.828040,4.412200,12605.154000,25.106000,2021.032000,3862.358000
std,144.481833,6.801869,0.255032,24759.378719,68.100294,5.116183,2368.629814
min,1.000000,4.230000,3.600000,85.000000,1.000000,1965.000000,30.000000
25%,125.750000,11.207500,4.200000,1952.750000,6.000000,2019.000000,1789.750000
50%,250.500000,15.945000,4.400000,3893.000000,12.000000,2022.000000,3735.000000
75%,375.250000,21.930000,4.600000,10986.500000,22.000000,2024.000000,5555.250000
max,500.000000,34.090000,5.000000,220000.000000,1200.000000,2026.000000,9600.000000

In [5]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            500 non-null    int64
 1   Title           500 non-null    str
 2   Author          500 non-null    str
 3   Category        500 non-null    str
 4   Sub-Genre       500 non-null    str
 5   Format          500 non-null    str
 6   Price (USD)     500 non-null    float64
 7   Rating          500 non-null    float64
 8   Reviews         500 non-null    float64
 9   Weeks on List   500 non-null    float64
 10  Publisher       500 non-null    str
 11  Year Published  500 non-null    float64
 12  ISBN            500 non-null    str
 13  Amazon BSR      500 non-null    float64
 14  Amazon URL      500 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 58.7 KB

In [12]:
dt['ISBN'] =pd.to_numeric(dt['ISBN'].str.replace('-', ''), errors='coerce')

In [13]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            500 non-null    int64
 1   Title           500 non-null    str
 2   Author          500 non-null    str
 3   Category        500 non-null    str
 4   Sub-Genre       500 non-null    str
 5   Format          500 non-null    str
 6   Price (USD)     500 non-null    float64
 7   Rating          500 non-null    float64
 8   Reviews         500 non-null    float64
 9   Weeks on List   500 non-null    float64
 10  Publisher       500 non-null    str
 11  Year Published  500 non-null    float64
 12  ISBN            500 non-null    int64
 13  Amazon BSR      500 non-null    float64
 14  Amazon URL      500 non-null    str
dtypes: float64(6), int64(2), str(7)
memory usage: 58.7 KB

In [14]:
dt.head()

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
0,1,The Let Them Theory,Mel Robbins,Non-Fiction,Self-Help,Paperback,14.99,4.7,98000.0,52.0,Hay House,2024.0,9781132788594,112.0,View
1,2,The Dinner Party,Freida McFadden,Fiction,Psychological Thriller,Paperback,11.69,4.3,1800.0,12.0,Sourcebooks Landmark,2025.0,9783762377160,175.0,View
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,9784303793205,64.0,View
3,4,The Correspondent: A Novel,Virginia Evans,Fiction,Literary Fiction,Hardcover,19.58,4.6,87363.0,28.0,Random House,2025.0,9786203286654,143.0,View
4,5,Atomic Habits,James Clear,Non-Fiction,Self-Help / Productivity,Paperback,16.99,4.8,120000.0,220.0,Avery,2018.0,9787933209545,237.0,View