In [1]:
import pandas as pd

In [2]:
dt = pd.read_csv('Amazon_BestSelling_Books_500.csv')

In [3]:
dt.head()

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
0,1,The Let Them Theory,Mel Robbins,Non-Fiction,Self-Help,Paperback,14.99,4.7,98000.0,52.0,Hay House,2024.0,978-1-13278-859-4,112.0,View
1,2,The Dinner Party,Freida McFadden,Fiction,Psychological Thriller,Paperback,11.69,4.3,1800.0,12.0,Sourcebooks Landmark,2025.0,978-3-76237-716-0,175.0,View
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,978-4-30379-320-5,64.0,View
3,4,The Correspondent: A Novel,Virginia Evans,Fiction,Literary Fiction,Hardcover,19.58,4.6,87363.0,28.0,Random House,2025.0,978-6-20328-665-4,143.0,View
4,5,Atomic Habits,James Clear,Non-Fiction,Self-Help / Productivity,Paperback,16.99,4.8,120000.0,220.0,Avery,2018.0,978-7-93320-954-5,237.0,View

In [4]:
dt.describe()

,Rank,Price (USD),Rating,Reviews,Weeks on List,Year Published,Amazon BSR
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,16.828040,4.412200,12605.154000,25.106000,2021.032000,3862.358000
std,144.481833,6.801869,0.255032,24759.378719,68.100294,5.116183,2368.629814
min,1.000000,4.230000,3.600000,85.000000,1.000000,1965.000000,30.000000
25%,125.750000,11.207500,4.200000,1952.750000,6.000000,2019.000000,1789.750000
50%,250.500000,15.945000,4.400000,3893.000000,12.000000,2022.000000,3735.000000
75%,375.250000,21.930000,4.600000,10986.500000,22.000000,2024.000000,5555.250000
max,500.000000,34.090000,5.000000,220000.000000,1200.000000,2026.000000,9600.000000

In [5]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            500 non-null    int64
 1   Title           500 non-null    str
 2   Author          500 non-null    str
 3   Category        500 non-null    str
 4   Sub-Genre       500 non-null    str
 5   Format          500 non-null    str
 6   Price (USD)     500 non-null    float64
 7   Rating          500 non-null    float64
 8   Reviews         500 non-null    float64
 9   Weeks on List   500 non-null    float64
 10  Publisher       500 non-null    str
 11  Year Published  500 non-null    float64
 12  ISBN            500 non-null    str
 13  Amazon BSR      500 non-null    float64
 14  Amazon URL      500 non-null    str
dtypes: float64(6), int64(1), str(8)
memory usage: 58.7 KB

In [6]:
dt['ISBN'] =pd.to_numeric(dt['ISBN'].str.replace('-', ''), errors='coerce')

In [7]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            500 non-null    int64
 1   Title           500 non-null    str
 2   Author          500 non-null    str
 3   Category        500 non-null    str
 4   Sub-Genre       500 non-null    str
 5   Format          500 non-null    str
 6   Price (USD)     500 non-null    float64
 7   Rating          500 non-null    float64
 8   Reviews         500 non-null    float64
 9   Weeks on List   500 non-null    float64
 10  Publisher       500 non-null    str
 11  Year Published  500 non-null    float64
 12  ISBN            500 non-null    int64
 13  Amazon BSR      500 non-null    float64
 14  Amazon URL      500 non-null    str
dtypes: float64(6), int64(2), str(7)
memory usage: 58.7 KB

In [8]:
dt.head()

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
0,1,The Let Them Theory,Mel Robbins,Non-Fiction,Self-Help,Paperback,14.99,4.7,98000.0,52.0,Hay House,2024.0,9781132788594,112.0,View
1,2,The Dinner Party,Freida McFadden,Fiction,Psychological Thriller,Paperback,11.69,4.3,1800.0,12.0,Sourcebooks Landmark,2025.0,9783762377160,175.0,View
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,9784303793205,64.0,View
3,4,The Correspondent: A Novel,Virginia Evans,Fiction,Literary Fiction,Hardcover,19.58,4.6,87363.0,28.0,Random House,2025.0,9786203286654,143.0,View
4,5,Atomic Habits,James Clear,Non-Fiction,Self-Help / Productivity,Paperback,16.99,4.8,120000.0,220.0,Avery,2018.0,9787933209545,237.0,View

In [9]:
dt.isnull()

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
dt.isnull().sum()

Rank              0
Title             0
Author            0
Category          0
Sub-Genre         0
Format            0
Price (USD)       0
Rating            0
Reviews           0
Weeks on List     0
Publisher         0
Year Published    0
ISBN              0
Amazon BSR        0
Amazon URL        0
dtype: int64

In [11]:
dt.loc[dt['Price (USD)']==16.99]

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
4,5,Atomic Habits,James Clear,Non-Fiction,Self-Help / Productivity,Paperback,16.99,4.8,120000.0,220.0,Avery,2018.0,9787933209545,237.0,View
139,140,River of Roses,Tony Robbins,Non-Fiction,Spirituality / Religion,Paperback,16.99,4.2,397.0,13.0,Tor Books,2026.0,9786844985305,4755.0,View

In [14]:
dt.loc[(dt['Rating']>4.7)&(dt['Reviews']>10000)].head()

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,9784303793205,64.0,View
4,5,Atomic Habits,James Clear,Non-Fiction,Self-Help / Productivity,Paperback,16.99,4.8,120000.0,220.0,Avery,2018.0,9787933209545,237.0,View
6,7,House of Flame and Shadow,Sarah J. Maas,Fiction,Romantasy,Hardcover,22.49,4.8,42000.0,32.0,Bloomsbury Publishing,2024.0,9789512453177,460.0,View
10,11,Dog Man: Big Jim Believes,Dav Pilkey,Fiction,Children's / Graphic Novel,Hardcover,9.49,4.9,12000.0,15.0,Graphix,2024.0,9788100747135,375.0,View
11,12,"Oh, the Places You'll Go!",Dr. Seuss,Fiction,Children's Picture Book,Hardcover,12.99,4.9,60000.0,1200.0,Random House,1990.0,9787190718788,387.0,View

In [16]:
dt.iloc[0:3,0:3]

   Rank                Title           Author
0     1  The Let Them Theory      Mel Robbins
1     2     The Dinner Party  Freida McFadden
2     3    Project Hail Mary        Andy Weir

In [19]:
dt['Year Published'].value_counts()

Year Published
2024.0    63
2025.0    60
2023.0    57
2026.0    56
2020.0    44
2021.0    39
2022.0    36
2019.0    30
2018.0    29
2016.0    23
2017.0    19
2015.0    15
2012.0     7
2014.0     6
2010.0     5
2011.0     4
2013.0     3
1990.0     1
1997.0     1
1965.0     1
1985.0     1
Name: count, dtype: int64

In [23]:
dt.sort_values('Rating',ascending=False).head(10)

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
476,477,Signal System,Cassandra Clare,Fiction,Dark Romance,Kindle Edition,9.83,5.0,1889.0,10.0,Riverhead Books,2022.0,9788647986511,9600.0,View
403,404,Where Shadow,Ta-Nehisi Coates,Non-Fiction,Personal Finance,Hardcover,23.62,5.0,473.0,5.0,Park Row,2015.0,9784560098286,4854.0,View
330,331,Mirror Undone,Jonathan Haidt,Non-Fiction,Celebrity Memoir,Hardcover,22.10,5.0,1286.0,15.0,Rodale Books,2023.0,9788487615296,7918.0,View
289,290,The Princess of Ice,Susanna Clarke,Fiction,Paranormal Romance,Hardcover,18.89,5.0,3826.0,15.0,Flatiron Books,2024.0,9782169323795,4016.0,View
119,120,Prince of Ice,Virginia Evans,Fiction,Cozy Mystery,Paperback,16.50,5.0,6575.0,23.0,Entangled: Red Tower Books,2026.0,9786283439091,4342.0,View
207,208,Voice Approach,Dean Koontz,Fiction,Horror,Kindle Edition,11.84,5.0,3587.0,9.0,Doubleday,2018.0,9789566652591,1398.0,View
261,262,The Ice Untold,Jodi Picoult,Fiction,Children's Picture Book,Paperback,11.52,5.0,2154.0,1.0,Workman Publishing,2025.0,9782875648562,5923.0,View
333,334,The Hero Code,Doris Kearns Goodwin,Non-Fiction,Business / Leadership,Paperback,16.05,4.9,4742.0,11.0,Hoover Ink,2016.0,9788424572075,4898.0,View
276,277,The Ocean Unbound,Paul Tremblay,Fiction,Middle Grade,Paperback,16.14,4.9,4785.0,9.0,Hachette Book Group,2025.0,9786783896003,5400.0,View
151,152,The Detective Revisited,Robin McKinley,Fiction,Science Fiction,Hardcover,26.96,4.9,4013.0,7.0,Convergent Books,2015.0,9783449346460,2101.0,View

In [24]:
dt['Sub-Genre'].unique()

<StringArray>
[                 'Self-Help',     'Psychological Thriller',
            'Science Fiction',           'Literary Fiction',
   'Self-Help / Productivity',                  'Romantasy',
        'Psychology / Health',       'Psychology / Society',
 'Children's / Graphic Novel',    'Children's Picture Book',
        'Activity / Coloring',             'Gift / Journal',
               'YA Dystopian',                     'Memoir',
         'Historical Fiction',            'Climate Fiction',
             'Art / Activity',       'Contemporary Romance',
           'Celebrity Memoir',      'Business / Psychology',
         'Health / Longevity',        'History / Adventure',
       'True Crime / History',           'Creativity / Art',
         'Business / Finance',           'Personal Finance',
         'Self-Help / Memoir',           'Science / Nature',
               'Middle Grade',             'Cooking / Food',
    'Spirituality / Religion',              'Graphic Novel',
               'Dark Romance',                'Space Opera',
                    'Fantasy',          'Crime / Detective',
               'Productivity',         'Politics / Society',
                  'Biography',                 'YA Romance',
              'Urban Fantasy',                     'Horror',
         'Paranormal Romance',               'Cozy Mystery',
      'Business / Leadership',                  'Parenting',
                 'True Crime',                    'History']
Length: 48, dtype: str

In [35]:
dt2=dt.drop(columns=['Author','Amazon BSR','Publisher','Year Published','Sub-Genre'])
dt2.head()

,Rank,Title,Category,Format,Price (USD),Rating,Reviews,Weeks on List,Amazon URL
0,1,The Let Them Theory,Non-Fiction,Paperback,14.99,4.7,98000.0,52.0,View
1,2,The Dinner Party,Fiction,Paperback,11.69,4.3,1800.0,12.0,View
2,3,Project Hail Mary,Fiction,Paperback,12.99,4.8,130000.0,108.0,View
3,4,The Correspondent: A Novel,Fiction,Hardcover,19.58,4.6,87363.0,28.0,View
4,5,Atomic Habits,Non-Fiction,Paperback,16.99,4.8,120000.0,220.0,View